config/routes.rb
Periop::Application.routes.draw do

  #
  #constraints(:host => "localhost") do
  #  match "(*x)" => redirect {|params, request|
  #    URI.parse(request.url).tap { |x| x.scheme = "https"}.tap { |x| x.host = "www.#{x.host}" }.to_s
  #}
  #end

  constraints(:host => "periop.com.au") do
    match "(*x)" => redirect {|params, request|
      URI.parse(request.url).tap { |x| x.host = "www.#{x.host}" }.tap { |x| x.scheme = "https"}.to_s
    }
  end

  resources :categories

  resources :forms
  resources :concepts

  get 'contact' => "contact_mails#new"
  post 'contact' => "contact_mails#create"

  #devise_for :patients, :path_prefix => 'd'

  resources :patients do
    resources :assessments ,:only => [:edit,:update,:show,:unassigned,:index,:create] do
      get 'unassigned', :on => :collection
      put 'unassigned', :on => :collection
      put 'assign'
      put 'unassign'
    end
    get 'operation_assessment_form' => 'assessments#operation_assessment_form'
    get 'clinician_assessment_form' => 'assessments#clinician_assessment_form'
    get 'loading_screen' => 'assessments#loading_screen'
    get 'note_assessment_form'      => 'assessments#note_assessment_form'
    resource :summary, :only => [:show,:show_printable] do
      get 'show_printable'
    end
  end



  resources :assessments ,:only => [:show,:destroy,:patient_assessment_form] do
    get "unassigned" => "assessments#unassigned",:on => :collection
    resource :assessment_summary,:as => :summary ,:only => [:show,:show_printable] do
      get 'show_printable'
    end
  end
  get "patient_assessment_form" => "assessments#patient_assessment_form"
  post "patient_assessment_form" => "assessments#update_patient_assessment"
  #post "operation_assessment_form" => "assessments#update_operation_assessment"

  resources :questions

  resources :professionals do
    post 'reset_password', :on => :member
  end


  authenticated :user do
    root :to => 'home#index'
  end

  root :to => "home#index"

  get 'privacy' => "home#privacy"
  get 'tos' => "home#tos"

  if (Rails.application.config.registerable)
    devise_for :users ,:controllers => {:registrations => "registrations"}
  else
    devise_for :users, :skip => [:registrations]
        as :user do
          get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
          put 'users' => 'devise/registrations#update', :as => 'user_registration'
        end
  end

  resources :users, :only => [:show, :index]

end

app/models/assessment.rb
class Assessment
  include Mongoid::Document

  NOT_STARTED = 'not started'
  STARTED_BUT_INCOMPLETE = 'Started but incomplete'
  COMPLETE = 'Complete'


  field :status, :type => String, :default => NOT_STARTED
  field :date_started, :type => DateTime
  field :updated_by, :type => String
  field :name, :type => String
  field :doctor_name, :type => String

  belongs_to :patient

  embeds_many :answers
  accepts_nested_attributes_for :answers
  field :anesthetist_id, :type => String

  validate :answers_empty

  def answers_empty
   if answers.all?{|answer| answer.value_to_s.blank? }
     errors.add(:base, 'All answers can\'t be blank')
   end
  end

  def self.create_for_patient(form, patient)
    assessment = self.new
    assessment.name = form.name
    assessment.patient= patient
    assessment
  end

  def answer question
    answers.where(:question_id => question._id).first
  end

  def self.unassigned
    where(patient_id: nil)
  end

  def answers_exist_in_form?
    questions_array = self.form.questions.map {|q| q._id}
    result = true
    self.answers.each  do |a|
      if a.question_id.nil?
        result = false
        message = '!!! assessment : ' + self._id.to_s + ' has answer that does not have question id ' +  a._id.to_s
        logger.error message
        puts message
      elsif !questions_array.include? a.question_id
        message = '!!! assessment : ' + self._id.to_s + ' has answer : ' + a._id.to_s + ' to question: ' + a.question_id.to_s + '  that not exist in form '
        logger.error message
        puts message
        result = false
      end
    end
    result
  end

  def answers_unique?
    result = true
    self.form.questions.each do |q|
      question_answers = self.answers.where(:question_id => q._id)
      if question_answers.size > 1
        message = '!!!  assessment  ' + self._id.to_s + ' is invalid ' + ' question ' +
            q.concept.name.to_s + ' have more than one answers:' + question_answers.all.map{|a| a.value_to_s }.to_s
        logger.error message
        puts message
        result = false
      end
    end
    result
  end


  def find_or_create_answer question
    answers.find_or_create_by(:question_id => question._id)
  end

  def self.status_list
    [NOT_STARTED, STARTED_BUT_INCOMPLETE, COMPLETE]
  end

  def update_assessment params, current_user
    result = true
    set_update_by(current_user)
    self.date_started = Time.now
    if result
      result = update_attributes(params)
    end
    #TODO remove?
    self.patient.update_values
    result
  end

  def set_update_by(current_user)
    professional_name = current_user.professional.name.to_s
    self.updated_by= professional_name
  end

  def find_or_create_answer_by_concept_name concept_name
    self.find_or_create_answer(find_question_by_concept_name (concept_name))
  end

  def find_answer_by_concept_name concept_name
    question = find_question_by_concept_name concept_name
    if !question
      return nil
    end
    self.answer(question)
  end


  def find_answer_value_by_concept_name concept
    answer = find_answer_by_concept_name concept
    if answer.nil?
      return ""
    end
    result = answer.value_to_s
    #puts 'find_answer_value_by_concept_name ' + concept + ' value: ' + result.to_s
    result
  end


  def find_question_by_concept_name concept_name
    concept = Concept.find_by_name(concept_name)
    self.form.questions.by_concept(concept)
  end

  def start_and_complete_assessment
    self.date_started = Time.now
    self.status= COMPLETE
    self.updated_by = 'Patient'
  end

  def completed?
    !self.date_started.nil? && self.status == COMPLETE
  end

  def date_str
    self.date_started.nil? ? " " : self.date_started.to_date.to_s
  end

  def summary
    self.name + " " +  date_str + ' status: ' + self.status
  end

  def get_anesthetist_id
    if !self.doctor_name.nil? && !self.doctor_name.blank?
      professional = Professional.find_by_name doctor_name
      return professional._id if !professional.nil?
    end
    answer  = self.find_answer_by_concept_name 'anesthetist'
    if (!answer.nil?)&&(!answer[:id_value].nil?)&&(!answer[:id_value].blank?)
      answer[:id_value]
    end
  end

  def get_anesthetist
    id = get_anesthetist_id
    if (!id.nil?)
      Professional.find(id)
    end
  end

  #
  #concept = Concept.find_by_name(concept_name)
  #self.form.questions.where(concept_id: concept._id).first


  def self.find_possible_matches_by_patient patient
    self.find_possible_matches [patient.firstname, patient.surname]
  end

  def self.find_possible_matches array
    #also_in({"answers.value" => array})
    where({"answers.value" => {"$in" => array}})
  end

  def form
    if self.name
      if self.name.eql? Form::PATIENT_ASSESSMENT
        return Form.patient_form_by_professional_name self.doctor_name
      else
        return Form.find_by_name(self.name)
      end
    else
      return Form.find(self.form_id)
    end
  end

  def form= form
    self.name= form.name
    self.doctor_name= Professional.find(form.professional_id).name if !form.professional_id.nil?
  end

  def patient_assesment_title
    find_answer_value_by_concept_name("patient_first_name") + " " +
    find_answer_value_by_concept_name("patient_surname") + " " +
    find_answer_value_by_concept_name("patient_dob").to_s
  end

  def summary_preparation
    "#{name} #{updated_by} #{date_str}"
  end
end

app/controllers/assessments_controller.rb
class AssessmentsController < ApplicationController
  load_resource :patient,:except => [:patient_assessment_form,:update_patient_assessment]
  load_and_authorize_resource :assessment,:new => [:patient_assessment_form,:operation_assessment_form,
                                                   :clinician_assessment_form, :note_assessment_form,
                                                   :update_patient_assessment]
  #, :through => :patient


  # GET /patient/.id/assessments/unassigned.json
  def unassigned
    if !params[:patient_id].nil?
      @patient = Patient.find(params[:patient_id])
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: AssessmentsDatatable.new(view_context,current_ability,@patient)}
    end
  end

  def index
    if !params[:patient_id].nil?
      @patient = Patient.find(params[:patient_id])
    end
    @assessments = Assessment.where(:patient_id => @patient._id).paginate(:page => params[:page])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @assessments }
    end
  end


  # GET /assessments/1
  # GET /assessments/1.json
  def show
    #@assessment = Assessment.find(params[:id])
    #if !params[:patient_id].nil?
    #  @patient = Patient.find(params[:patient_id])
    #end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @assessment }
    end
  end

  def summary
    #@patient = Patient.find(params[:patient_id])
    @concepts = Concept.all
    @assessments = @patient.assessments
    respond_to do |format|
      format.html
      format.json { render json: @assessment }
    end
  end

  # GET /assessments/new
  # GET /assessments/new.json
  def new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @assessment }
    end
  end

  # GET /assessments/1/edit
  def edit
    #@assessment = Assessment.find(params[:id])
    @questions = @assessment.form.questions
    @url = patient_assessment_path(@patient,@assessment)
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @assessment}
    end
  end

  # GET /patient_assessment_form
  def patient_assessment_form
    #@assessment = Assessment.new
    @assessment.form= Form.patient_form(params[:doctor])
    @questions = @assessment.form.questions
  end

  def operation_assessment_form
      base_assessment_form Form::NEW_OPERATION
  end

  def loading_screen
    @url = ERB::Util.html_escape(params[:q])

    params[:q] = nil
    render "loading"
  end

  def clinician_assessment_form
    base_assessment_form Form::CLINIC_ASSESSMENT
  end

  def note_assessment_form
      base_assessment_form Form::QUICK_NOTE_ASSESSMENT
  end

  def base_assessment_form form_name
    @assessment.patient= @patient
    @assessment.form= Form.find_by_name(form_name)
    @questions = @assessment.form.questions
    @url = patient_assessments_path(@patient)
    render "new"
  end

  def create
    @assessment.patient= @patient
    @assessment.set_update_by(current_user)
    @assessment.status= Assessment::COMPLETE
    @url = patient_assessments_path(@patient)
      respond_to do |format|
        if @assessment.save
          format.html { redirect_to @patient, notice: 'Assessment was successfully created.' }
          format.json { head :no_content }
        else
          format.html { render action: "new" }
          format.json { render json: @assessment.errors, status: :unprocessable_entity }
        end
      end
  end


  # PUT /assessments/1
  # PUT /assessments/1.json
  def update
    #@assessment = Assessment.find(params[:id])
    @assessment.set_update_by(current_user)
    respond_to do |format|
      if @assessment.save
        format.html { redirect_to patient_path, notice: 'Assessment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @assessment.errors, status: :unprocessable_entity }
      end
    end
  end

  def assign
    # TODO enable load_and_authorize
    @assessment = Assessment.find(params[:assessment_id])
    #@patient = Patient.find(params[:patient_id])
    @assessment.patient= @patient
    @patient.update_values
    respond_to do |format|
      if @assessment.save
        format.html { redirect_to patient_assessment_path(@patient, @assessment), notice: 'Assessment assigned.'}
        format.json { head :no_content }
      else
        format.html { render action: "show" }
        format.json { render json: @assessment.errors, status: :unprocessable_entity }
      end
    end
  end

  def unassign
    @assessment = Assessment.find(params[:assessment_id])
    #@patient = Patient.find(params[:patient_id])
    @assessment.patient= nil
    @patient.update_values
    respond_to do |format|
      if @assessment.save
        format.html { redirect_to patient_assessment_path(@patient, @assessment), notice: 'Assessment unassigned.'}
        format.json { head :no_content }
      else
        format.html { render action: "show" }
        format.json { render json: @assessment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_patient_assessment
    #@assessment = Assessment.new(params[:assessment])
    @assessment.form= Form.patient_form_by_professional_name(params[:assessment][:doctor_name])
    @assessment.start_and_complete_assessment
    respond_to do |format|
      if @assessment.save
        anesthetist = @assessment.get_anesthetist
        if !anesthetist.nil?
          AssessmentMailer.patient_assessment_mail(anesthetist).deliver
        end
        format.html { redirect_to root_path, notice: 'Thank you, your assessment has been sent to your doctor.' }
        format.json { render json: @assessment, status: :created, location: @assessment }
      else
        format.html { render action: "patient_assessment_form" }
        format.json { render json: @assessment.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /assessments/1
  # DELETE /assessments/1.json
  def destroy
    #@assessment = Assessment.find(params[:id])
    @assessment.destroy

    respond_to do |format|
      if @patient.nil?
        format.html {redirect_to root_path , notice: 'Assessment was successfully deleted.' }
        format.json { head :no_content }
      else
        format.html {redirect_to @patient, notice: 'Assessment was successfully deleted.' }
        format.json { head :no_content }
      end
    end
  end
end

app/helpers/assessments_helper.rb
module AssessmentsHelper
  def answer_for(question_name,assessment)
    q = Question.where(:display_name => question_name).first

    if !q.nil? && !assessment.answers.nil? && assessment.answers.size >0
      assessment.answers.where(:question_id => q._id).first.value_to_s
    end
  end
end

app/views/assessments/_answer.html.haml
- question = a.object.question
- label = question.display_name if !question.nil?
- if question.input_type == 'Start_section'
  !="<div class=\"accordion-group\">"
  .navbar-inner.heading
    %h4
      =label
  !="<section class=\"accordion-body\">"
- else if question.input_type == 'End_section'
  !="</section>"
  !="</div>"
  - else
    %fieldset{:data => {:condition => question.condition }}
      %legend
        !=label
      - label = "Answer"
      = a.input :question_id, :as => :hidden
      - if (question.input_type == 'OneOption')
        = a.input :value,:label => label,:as => :select , :collection => question.option_list,:include_blank => false,
        :label_method => :label , :value_method => :value,
        :input_html => {:data => {:short_name => question.concept.name.downcase, :condition => question.condition },
        :class => 'question'}
        - else if (question.input_type == 'ManyOptions')
          = a.input :array_value,:label => label,:as => :check_boxes, :collection => question.option_list,:include_blank => false,
          :label_method => :label , :value_method => :value,
          :input_html => {:multiple => "multiple" ,:data => {:short_name => question.concept.name.downcase, :condition => question.condition },
          :class => 'question'}
          - else if question.input_type == 'Date'
            = a.input :date_value, :label => label,
            :order => [:day , :month, :year],
            :include_blank => true,
            :input_html => {:data => {:short_name => question.concept.name.downcase,:start_date => question.start_date.to_s, :end_date => question.end_date.to_s,
            :condition => question.condition}, :class => 'question datepicker'}
          - else if (question.input_type == 'Text_box')
            =a.input :value,:as => :text,:label => label,
            :input_html => {:rows => 5,:cols => 60,:data => {:short_name => question.concept.name.downcase, :condition => question.condition }, :class => 'question'}
            - else if (question.input_type == 'Lookup_User_Anesthetist')
              = a.input :id_value,:label => label,:as => :select , :collection => anesthetists_option_list,:include_blank => true,
                      :label_method => :name , :value_method => :_id,
                      :input_html => {:data => {:short_name => question.concept.name.downcase, :condition => question.condition },
                      :class => 'question anesthetist-select'}
              - else if (question.input_type == 'Statement')
                - else
                  = a.input :value,:label => label ,
                  :input_html => {:data => {:short_name => question.concept.name.downcase, :condition => question.condition }, :class => 'question'}
      - if (question.ask_details == "Y")
        =a.input :details,:label => "Please provide more information",:as => :text,:input_html => {:data => {:short_name => question.concept.name.downcase + "_details", :condition => question.details_criteria},
        :class => 'question question_details', :rows => 5}

app/views/assessments/_assign_form.html.haml
- if @assessment.patient.nil?
  = link_to( 'Assign assessment to patient', patient_assessment_assign_path(@patient,@assessment), :method => :put,:class=> "btn btn-primary")
- else
  = link_to( 'Unassign assessment', patient_assessment_unassign_path(@patient,@assessment), :method => :put,:class=> "btn btn-primary")

app/views/assessments/_form.html.haml
%h3 #{@assessment.name}
- form_disabled ||= false
- url = @url.nil? ? patient_assessment_form_path : @url
- assessment = setup_assessment(@assessment)
= simple_form_for(assessment,:url => url,
:html => {:class => 'assessment' ,:disabled => form_disabled },
:defaults => {:disabled => form_disabled}) do |f|
  = f.error_notification
  = f.error :base, {:class => "alert alert-error"}
  = assessment.errors.full_messages.to_sentence if Rails.env.development?
  .form-inputs
    = f.input :name, :as => :hidden
    = f.input :doctor_name, :as => :hidden
    = f.simple_fields_for :answers do |a|
      - question = a.object.question
      - if question.nil?
        ''
      - else
        = render "assessments/answer",:a => a
    - if assessment[:contains_dob] != true && !@assessment.patient.nil?
      %input{:type => :hidden , :data => {:"short-name" => "patient_dob"}, :value => @assessment.patient.dob}
    - if user_signed_in?
      - if current_user.professional?
        = f.input :status,:as => :hidden, :collection => Assessment.status_list
  - if !form_disabled
    .form-actions
      = f.button :submit,:value => 'Submit',:disable_with => 'Submitting'

app/views/assessments/edit.html.haml
%h1 Editing assessment
= render 'patients/nav'
= render('patients/detailed_info')
= render 'form'
= render 'patients/nav'

app/views/assessments/index.html.haml
%h1 Listing assessments

%table{:class => "table table-striped table-bordered" }
  %thead
    %tr
      %th Status
      %th Type
      %th
  %tbody
    - @assessments.each do |assessment|
      %tr
        %td= assessment.status
        %td= assessment.name
        %td
          -if @patient
            = link_to( 'Show', patient_assessment_path(@patient,assessment))
          -#- else
          -#  = link_to 'Show', assessment


%br
%p
  - if (can? :edit, @patient) && !@patient.patient_assessment_assigned?
    =link_to('Find patient assessment', unassigned_patient_assessments_path(@patient))

app/views/assessments/loading.html.haml
%h1 New assessment
= render 'patients/nav'
- if !@patient.nil?
  =render 'patients/detailed_info'
#form_placeholder.loading
  -#%h2.centered loading
= render 'patients/nav'

:javascript
  loadData = function (){
  var url = '#{@url}';
  $.get(url, function(data) {data;
  $('#form_placeholder').removeClass('loading')
  },"script");

  }
  loadData();

app/views/assessments/new.html.haml
%h1 New assessment
= render 'patients/nav'
- if !@patient.nil?
  =render 'patients/detailed_info'
= render 'form'
= render 'patients/nav'

app/views/assessments/new.js.haml
:plain
  $('#form_placeholder').html("#{ escape_javascript(render('form')) }")
  window.checkAllDocument()
  window.datepicker()
  window.accordion()

app/views/assessments/patient_assessment_form.html.haml
%h1 All information is confidential.
= render 'form'

app/views/assessments/show.html.haml
= render 'patients/nav'
-if !@patient.nil?
  = render('patients/detailed_info')
  -if @assessment.form.patient_form?
    = render 'assign_form'
    = link_to 'Delete assessment', @assessment, :confirm => 'Are you sure?', :method => :delete,:class=> "btn btn-danger"
= render 'form', :form_disabled => true
= render 'patients/nav'

app/views/assessments/unassigned.html.haml
%h1 Patient Assessments
= render('patients/nav')
- if !@patient.nil?
  =render 'patients/detailed_info'
  - source = unassigned_patient_assessments_url(@patient,format: "json")
- else
  - source = unassigned_assessments_url(format: "json")
%br
%br
%table#assessments{:data => {:source => source}, :class => "table table-striped table-bordered centered" }
  %thead
    %tr
      %th Surname
      %th Firstname
      %th DOB
      %th Form date
      %th Surgery date
      %th Surgeon
      %th
        %i.icon-list{:title => "Questionnaire"}
      %th
        %i.icon-folder-open{:title => "Assessment"}
      %th
        %i.icon-print{:title => "Printable"}
      %th
        %i.icon-plus{:title => "Join"}
      %th
        %i.icon-remove{:title => "Delete"}
  %tbody
%br
= render('patients/nav')