config/routes.rb
Periop::Application.routes.draw do

  #
  #constraints(:host => "localhost") do
  #  match "(*x)" => redirect {|params, request|
  #    URI.parse(request.url).tap { |x| x.scheme = "https"}.tap { |x| x.host = "www.#{x.host}" }.to_s
  #}
  #end

  constraints(:host => "periop.com.au") do
    match "(*x)" => redirect {|params, request|
      URI.parse(request.url).tap { |x| x.host = "www.#{x.host}" }.tap { |x| x.scheme = "https"}.to_s
    }
  end

  resources :categories

  resources :forms
  resources :concepts

  get 'contact' => "contact_mails#new"
  post 'contact' => "contact_mails#create"

  #devise_for :patients, :path_prefix => 'd'

  resources :patients do
    resources :assessments ,:only => [:edit,:update,:show,:unassigned,:index,:create] do
      get 'unassigned', :on => :collection
      put 'unassigned', :on => :collection
      put 'assign'
      put 'unassign'
    end
    get 'operation_assessment_form' => 'assessments#operation_assessment_form'
    get 'clinician_assessment_form' => 'assessments#clinician_assessment_form'
    get 'loading_screen' => 'assessments#loading_screen'
    get 'note_assessment_form'      => 'assessments#note_assessment_form'
    resource :summary, :only => [:show,:show_printable] do
      get 'show_printable'
    end
  end



  resources :assessments ,:only => [:show,:destroy,:patient_assessment_form] do
    get "unassigned" => "assessments#unassigned",:on => :collection
    resource :assessment_summary,:as => :summary ,:only => [:show,:show_printable] do
      get 'show_printable'
    end
  end
  get "patient_assessment_form" => "assessments#patient_assessment_form"
  post "patient_assessment_form" => "assessments#update_patient_assessment"
  #post "operation_assessment_form" => "assessments#update_operation_assessment"

  resources :questions

  resources :professionals do
    post 'reset_password', :on => :member
  end


  authenticated :user do
    root :to => 'home#index'
  end

  root :to => "home#index"

  get 'privacy' => "home#privacy"
  get 'tos' => "home#tos"

  if (Rails.application.config.registerable)
    devise_for :users ,:controllers => {:registrations => "registrations"}
  else
    devise_for :users, :skip => [:registrations]
        as :user do
          get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
          put 'users' => 'devise/registrations#update', :as => 'user_registration'
        end
  end

  resources :users, :only => [:show, :index]

end

app/models/concept.rb
  class Concept
  include Mongoid::Document

  cache

  field :name, :type => String
  field :display_name, :type => String
  field :order_in_category, :type => Integer
  field :position, :type => Integer

  field :conflict_resolution, :type => String

  ALL = "All"
  RECENT ="Recent"
  PROFESSIONAL = "Professional"
  PATIENT = "Patient"

  field :mpog_code, :type => String
  field :mpog_name, :type => String
  field :snomed_code, :type => String

  belongs_to :category
  has_many :questions

  def self.find_by_name namestr
    self.where(name: namestr).first
  end


  def self.sorted
    self.asc(:order_in_category)
  end

end

app/controllers/concepts_controller.rb
class ConceptsController < ApplicationController
  # GET /concepts
  # GET /concepts.json
  def index
    @concepts = Concept.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @concepts }
    end
  end

  # GET /concepts/1
  # GET /concepts/1.json
  def show
    @concept = Concept.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @concept }
    end
  end

  # GET /concepts/new
  # GET /concepts/new.json
  def new
    @concept = Concept.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @concept }
    end
  end

  # GET /concepts/1/edit
  def edit
    @concept = Concept.find(params[:id])
  end

  # POST /concepts
  # POST /concepts.json
  def create
    @concept = Concept.new(params[:concept])

    respond_to do |format|
      if @concept.save
        format.html { redirect_to @concept, notice: 'Concept was successfully created.' }
        format.json { render json: @concept, status: :created, location: @concept }
      else
        format.html { render action: "new" }
        format.json { render json: @concept.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /concepts/1
  # PUT /concepts/1.json
  def update
    @concept = Concept.find(params[:id])

    respond_to do |format|
      if @concept.update_attributes(params[:concept])
        format.html { redirect_to @concept, notice: 'Concept was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @concept.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /concepts/1
  # DELETE /concepts/1.json
  def destroy
    @concept = Concept.find(params[:id])
    @concept.destroy

    respond_to do |format|
      format.html { redirect_to concepts_url }
      format.json { head :no_content }
    end
  end
end

app/views/concepts/_form.html.haml
= simple_form_for(@concept) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :display_name
    = f.input :snomed_code
    = f.input :mpog_code
    = f.input :position

  .form-actions
    = f.button :submit

app/views/concepts/edit.html.haml
%h1 Editing concept

= render 'form'

= link_to 'Show', @concept
\|
= link_to 'Back', concepts_path

app/views/concepts/index.html.haml
%h1 Listing concepts

%table
  %tr
    %th Name
    %th Display name
    %th Snomed code
    %th Mpog code
    %th Position
    %th
    %th
    %th

  - @concepts.each do |concept|
    %tr
      %td= concept.name
      %td= concept.display_name
      %td= concept.snomed_code
      %td= concept.mpog_code
      %td= concept.position
      %td= link_to 'Show', concept
      %td= link_to 'Edit', edit_concept_path(concept)
      %td= link_to 'Destroy', concept, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Concept', new_concept_path

app/views/concepts/new.html.haml
%h1 New concept

= render 'form'

= link_to 'Back', concepts_path

app/views/concepts/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @concept.name
%p
  %b Display name:
  = @concept.display_name
%p
  %b Snomed code:
  = @concept.snomed_code
%p
  %b Mpog code:
  = @concept.mpog_code
%p
  %b Position:
  = @concept.position

= link_to 'Edit', edit_concept_path(@concept)
\|
= link_to 'Back', concepts_path