config/routes.rb
Periop::Application.routes.draw do

  #
  #constraints(:host => "localhost") do
  #  match "(*x)" => redirect {|params, request|
  #    URI.parse(request.url).tap { |x| x.scheme = "https"}.tap { |x| x.host = "www.#{x.host}" }.to_s
  #}
  #end

  constraints(:host => "periop.com.au") do
    match "(*x)" => redirect {|params, request|
      URI.parse(request.url).tap { |x| x.host = "www.#{x.host}" }.tap { |x| x.scheme = "https"}.to_s
    }
  end

  resources :categories

  resources :forms
  resources :concepts

  get 'contact' => "contact_mails#new"
  post 'contact' => "contact_mails#create"

  #devise_for :patients, :path_prefix => 'd'

  resources :patients do
    resources :assessments ,:only => [:edit,:update,:show,:unassigned,:index,:create] do
      get 'unassigned', :on => :collection
      put 'unassigned', :on => :collection
      put 'assign'
      put 'unassign'
    end
    get 'operation_assessment_form' => 'assessments#operation_assessment_form'
    get 'clinician_assessment_form' => 'assessments#clinician_assessment_form'
    get 'loading_screen' => 'assessments#loading_screen'
    get 'note_assessment_form'      => 'assessments#note_assessment_form'
    resource :summary, :only => [:show,:show_printable] do
      get 'show_printable'
    end
  end



  resources :assessments ,:only => [:show,:destroy,:patient_assessment_form] do
    get "unassigned" => "assessments#unassigned",:on => :collection
    resource :assessment_summary,:as => :summary ,:only => [:show,:show_printable] do
      get 'show_printable'
    end
  end
  get "patient_assessment_form" => "assessments#patient_assessment_form"
  post "patient_assessment_form" => "assessments#update_patient_assessment"
  #post "operation_assessment_form" => "assessments#update_operation_assessment"

  resources :questions

  resources :professionals do
    post 'reset_password', :on => :member
  end


  authenticated :user do
    root :to => 'home#index'
  end

  root :to => "home#index"

  get 'privacy' => "home#privacy"
  get 'tos' => "home#tos"

  if (Rails.application.config.registerable)
    devise_for :users ,:controllers => {:registrations => "registrations"}
  else
    devise_for :users, :skip => [:registrations]
        as :user do
          get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
          put 'users' => 'devise/registrations#update', :as => 'user_registration'
        end
  end

  resources :users, :only => [:show, :index]

end

app/views/layouts/_google_analitics.html.haml
- if Rails.env.production?
  :javascript
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-33751374-1']);
      _gaq.push(['_setDomainName', 'pre-op.net']);
      _gaq.push(['_trackPageview']);
      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

app/views/layouts/_inspectlet.html.erb
<% if Rails.env.production? %>
<!-- Begin Inspectlet Embed Code -->
<script type="text/javascript" id="inspectletjs">
  window.__insp = window.__insp || [];
  __insp.push(['wid', 1417540681]);
  (function() {
    function __ldinsp(){var insp = document.createElement('script'); insp.type = 'text/javascript'; insp.async = true; insp.id = "inspsync"; insp.src = ('https:' == document.location.protocol ? 'https' : 'http') + '://cdn.inspectlet.com/inspectlet.js'; var x = document.getElementsByTagName('script')[0]; x.parentNode.insertBefore(insp, x); }
    if (window.attachEvent){
      window.attachEvent('onload', __ldinsp);
    }else{
      window.addEventListener('load', __ldinsp, false);
    }
  })();
</script>
<!-- End Inspectlet Embed Code -->
<% end %>

app/views/layouts/_messages.html.haml
- if (browser.ie6?) ||(browser.ie7?)
  %div{:class => "alert alert-error"}
    We're sorry but your browser will not work properly on this site.
    Please upgrade your browser
- flash.each do |name, msg|
  - if !msg.blank? && msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/_navigation.html.haml
= link_to Rails.application.config.site_url, root_path, :class => 'brand'
%ul.nav.pull-right
  - if user_signed_in? && current_user.admin?
    %li
      = link_to('Questions managment', questions_path)
    %li
      = link_to('Patients managment', patients_path)
    %li
      = link_to('Professionals management', professionals_path)
    %li
      %a{:href => '#'}Logged in as admin: #{current_user.name}
  - if user_signed_in?
    - if current_user.professional?
      %li
        %a{:href => '#'}Logged in as professional: #{current_user.name}
    %li
      = link_to('Logout', destroy_user_session_path, :method=>'delete')
  - else
    %li
      = link_to('Login', new_user_session_path)
    - if Rails.application.config.registerable
      %li
        = link_to "Sign up", new_user_registration_path
  - if user_signed_in?
    %li
      = link_to('Edit account', edit_user_registration_path)
  %li
    = link_to('Privacy', privacy_path)
  %li
    = link_to('Contact us', contact_path)

-#Log in, Sign up, Privacy, Contact

app/views/layouts/application.html.haml
!!!
%html
  %head
    = render 'layouts/inspectlet'
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %meta{:name => "c923fbd2f5592a094045a0867ff98cfc29534a83", :content => "ddf419e5f9f65b40885664eb7047140f78f51310"}
    %title= content_for?(:title) ? yield(:title) : "Periop.com.au"
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
    = render 'layouts/google_analitics'
  %body
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content{:class => yield(:content_class)}
          .row
            .span12
              = render 'layouts/messages'
              = yield
              = debug(params) if Rails.env.development?
          %footer

app/views/layouts/inspectlet.html.erb
<% if Rails.env.production? %>
<!-- Begin Inspectlet Embed Code -->
<script type="text/javascript" id="inspectletjs">
  window.__insp = window.__insp || [];
  __insp.push(['wid', 1417540681]);
  (function() {
    function __ldinsp(){var insp = document.createElement('script'); insp.type = 'text/javascript'; insp.async = true; insp.id = "inspsync"; insp.src = ('https:' == document.location.protocol ? 'https' : 'http') + '://cdn.inspectlet.com/inspectlet.js'; var x = document.getElementsByTagName('script')[0]; x.parentNode.insertBefore(insp, x); }
    if (window.attachEvent){
      window.attachEvent('onload', __ldinsp);
    }else{
      window.addEventListener('load', __ldinsp, false);
    }
  })();
</script>
<!-- End Inspectlet Embed Code -->
<% end %>

app/views/layouts/printer.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "Periop.com.au"
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    -#%script
    -#  window.onload = function() { window.print(); }
    = csrf_meta_tags
    = yield(:head)
  %body
    -#%header.navbar.navbar-fixed-top
    -#  %nav.navbar-inner
    -#    .container
    -#      = render 'layouts/navigation'
    #main{:role => "main",:class => "print"}
      .container
        .row
          .span12
            = render 'layouts/messages'
            = yield
            = debug(params) if Rails.env.development?
          -#%footer